name: Type check

on:
  push:
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pyright homeassistant beautifulsoup4 lxml

      - name: Run pyright
        run: pyright custom_components/mega
